//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FluentValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentValidationResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETPMS.Web.Properties.FluentValidationResources", typeof(FluentValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;长度不应大于{1}字符~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_LehgthShouldLitterThan {
            get {
                return ResourceManager.GetString("G_Msg_LehgthShouldLitterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;长度不应小于{1}字符~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_LengthShouldBigerThan {
            get {
                return ResourceManager.GetString("G_Msg_LengthShouldBigerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;长度应介于{1}-{2}字符之间~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_LengthShouldInRange {
            get {
                return ResourceManager.GetString("G_Msg_LengthShouldInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos;格式不正确，只能包含英文字母，数字，减号，下划线，并且以英文字母开头，且小长度为2，最大长度为20字符~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_SholdBeEntry {
            get {
                return ResourceManager.GetString("G_Msg_SholdBeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;不能晚于当前日期~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_ShouldGreaterThanCurrentDate {
            get {
                return ResourceManager.GetString("G_Msg_ShouldGreaterThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;不能晚于当前时间~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_ShouldGreaterThanCurrentTime {
            get {
                return ResourceManager.GetString("G_Msg_ShouldGreaterThanCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;不能早于当前日期~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_ShouldLitterThanCurrentDate {
            get {
                return ResourceManager.GetString("G_Msg_ShouldLitterThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;不能早于当前时间~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_ShouldLitterThanCurrentTime {
            get {
                return ResourceManager.GetString("G_Msg_ShouldLitterThanCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请明确&apos;{0}&apos;信息~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_ShouldNotEqual {
            get {
                return ResourceManager.GetString("G_Msg_ShouldNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;不应为空~ 的本地化字符串。
        /// </summary>
        internal static string G_Msg_ShouldNotNullOrEmpty {
            get {
                return ResourceManager.GetString("G_Msg_ShouldNotNullOrEmpty", resourceCulture);
            }
        }
    }
}
