//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_CONFIG
    {
        public int ID { get; set; }
        public int CONFIG_CATEGORY { get; set; }
        public string CONFIG_NAME { get; set; }
        public string CONFIG_VALUE { get; set; }
        public string CONFIG_DESCRIPTION { get; set; }
        public byte CONFIG_STATUS { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    }
}
