//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EP_CONTRACT()
        {
            this.EP_EQUIPMENT_TASK = new HashSet<EP_EQUIPMENT_TASK>();
        }
    
        public int ID { get; set; }
        public string CONTRACT_CODE { get; set; }
        public string CONTRACT_NAME { get; set; }
        public byte CONTRACT_TYPE_ID { get; set; }
        public byte CONTRACT_STATUS { get; set; }
        public string PROJECT_CODE { get; set; }
        public string PROJECT_NAME { get; set; }
        public int PLANT_ID { get; set; }
        public string PLANT_CONTRACTS { get; set; }
        public System.DateTime SIGNING_TIME { get; set; }
        public decimal CONTRACT_VALUE { get; set; }
        public decimal RECEIVABLE_VALUE { get; set; }
        public decimal RECEIVED_VALUE { get; set; }
        public decimal SUBCONTRACT_VALUE { get; set; }
        public byte SUBCONTRACT_PAYMENT { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TINE { get; set; }
    
        public virtual EP_POWER_PLANT EP_POWER_PLANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_EQUIPMENT_TASK> EP_EQUIPMENT_TASK { get; set; }
    }
}
