//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_CONTRACT_RELEQUIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EP_CONTRACT_RELEQUIPMENT()
        {
            this.OD_BASIC = new HashSet<OD_BASIC>();
        }
    
        public int ID { get; set; }
        public int MENUFACTURER_ID { get; set; }
        public byte EQUIPMENT_TYPE_ID { get; set; }
        public string EQUIPMENT_CODE { get; set; }
        public string EQUIPMENT_DESCRIPTION { get; set; }
        public System.DateTime PRODUCTION_TIME { get; set; }
        public byte USAGE_TYPE_ID { get; set; }
        public byte EXPERIMENT_STATUS { get; set; }
        public bool IS_DELETED { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        public virtual EP_EQUIPMENT_MENUFACTURER EP_EQUIPMENT_MENUFACTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_BASIC> OD_BASIC { get; set; }
    }
}
