//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_DELEGATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EP_DELEGATION()
        {
            this.EP_DELEGATION_RELEXPRESS = new HashSet<EP_DELEGATION_RELEXPRESS>();
            this.EP_DELEGATION_RELITEM = new HashSet<EP_DELEGATION_RELITEM>();
        }
    
        public int ID { get; set; }
        public int TASK_ID { get; set; }
        public string DELEGATION__CODE { get; set; }
        public System.DateTime DELEGATION_DATE { get; set; }
        public decimal DELEGATION_COST { get; set; }
        public byte DELEGATION_STATUS { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_CONTRACTS_NAME { get; set; }
        public string CLIENT_CONTRACT_INFORMATION { get; set; }
        public string SERVER_NAME { get; set; }
        public string SERVER_CONTRACTS_NAME { get; set; }
        public string SERVER_CONTRACT_INFORMATION { get; set; }
        public byte RECEIVING_TYPE_ID { get; set; }
        public byte REMAINING_PROCESSING_TYPE_ID { get; set; }
        public string REMARK { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_DELEGATION_RELEXPRESS> EP_DELEGATION_RELEXPRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_DELEGATION_RELITEM> EP_DELEGATION_RELITEM { get; set; }
        public virtual EP_EQUIPMENT_TASK EP_EQUIPMENT_TASK { get; set; }
    }
}
