//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_EQUIPMENT_MENUFACTURER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EP_EQUIPMENT_MENUFACTURER()
        {
            this.EP_CONTRACT_RELEQUIPMENT = new HashSet<EP_CONTRACT_RELEQUIPMENT>();
        }
    
        public int ID { get; set; }
        public string MENUFACTURER_NAME { get; set; }
        public string MENUFACTURER_SHORT_NAME { get; set; }
        public string MENUFACTURER_DESCRIPTION { get; set; }
        public string CONTRACTS_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public bool IS_DELETED { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_CONTRACT_RELEQUIPMENT> EP_CONTRACT_RELEQUIPMENT { get; set; }
    }
}
