//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_EQUIPMENT_TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EP_EQUIPMENT_TASK()
        {
            this.EP_DELEGATION = new HashSet<EP_DELEGATION>();
            this.EP_EXPERIMENT_DOCUMENT = new HashSet<EP_EXPERIMENT_DOCUMENT>();
        }
    
        public int ID { get; set; }
        public int CONTRACT_ID { get; set; }
        public string TASK_CODE { get; set; }
        public byte TASK_STATUS { get; set; }
        public string TASK_DESCRIPTION { get; set; }
        public int TASK_LEADER_ID { get; set; }
        public string TAST_STAFF_IDS { get; set; }
        public System.DateTime BEGIN_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string REMARK { get; set; }
        public int APPROVER_ID { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        public virtual EP_CONTRACT EP_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_DELEGATION> EP_DELEGATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_EXPERIMENT_DOCUMENT> EP_EXPERIMENT_DOCUMENT { get; set; }
        public virtual UM_USERINFO UM_USERINFO { get; set; }
        public virtual UM_USERINFO UM_USERINFO1 { get; set; }
    }
}
