//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_POWER_PLANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EP_POWER_PLANT()
        {
            this.EP_CONTRACT = new HashSet<EP_CONTRACT>();
        }
    
        public int ID { get; set; }
        public string PLANT_NAME { get; set; }
        public string PLANT_SHORT_NAME { get; set; }
        public string PLANT_DESCRIPTION { get; set; }
        public string CONTRACTS_NAME { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public bool IS_DELETED { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_CONTRACT> EP_CONTRACT { get; set; }
    }
}
