//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_BASIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OD_BASIC()
        {
            this.OD_BIAS = new HashSet<OD_BIAS>();
            this.OD_CRUSHER_GRANULARITY = new HashSet<OD_CRUSHER_GRANULARITY>();
            this.OD_ELECTRIC_DIVIDING_MACHINE = new HashSet<OD_ELECTRIC_DIVIDING_MACHINE>();
            this.OD_CRUSHING_DIVIDING_MACHINE = new HashSet<OD_CRUSHING_DIVIDING_MACHINE>();
            this.OD_CRUSHING_MACHINE = new HashSet<OD_CRUSHING_MACHINE>();
            this.OD_DIEVIDER_GRANULARITY = new HashSet<OD_DIEVIDER_GRANULARITY>();
            this.OD_INTEGRATED_PREPARATION_MACHINE = new HashSet<OD_INTEGRATED_PREPARATION_MACHINE>();
            this.OD_MILLER_GRANULARITY = new HashSet<OD_MILLER_GRANULARITY>();
            this.OD_MILLING_MACHINE = new HashSet<OD_MILLING_MACHINE>();
            this.OD_MT_LOSSES = new HashSet<OD_MT_LOSSES>();
            this.OD_RIFFLE_DEVIDING_MACHINE = new HashSet<OD_RIFFLE_DEVIDING_MACHINE>();
            this.OD_SAMPLING_MACHINE = new HashSet<OD_SAMPLING_MACHINE>();
            this.OD_SPLITTING_RATION = new HashSet<OD_SPLITTING_RATION>();
            this.OD_TEST_INSTRUMENT = new HashSet<OD_TEST_INSTRUMENT>();
            this.OD_WEIGHT_LOSSES = new HashSet<OD_WEIGHT_LOSSES>();
            this.OD_UNIFIED_PREPARATION_MACHINE = new HashSet<OD_UNIFIED_PREPARATION_MACHINE>();
        }
    
        public int ID { get; set; }
        public int CONTRACT_RELEQUIPMENT_ID { get; set; }
        public string RECODE_CODE { get; set; }
        public byte EQUIPMENT_TYPE_ID { get; set; }
        public string EQUIPMENT_DESCRIPTION { get; set; }
        public System.DateTime TEST_DATE { get; set; }
        public string TEST_INSTITUTION { get; set; }
        public string TEST_PERSONNEL { get; set; }
        public string SUPERVISORS { get; set; }
        public byte DATA_STATUS { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        public virtual EP_CONTRACT_RELEQUIPMENT EP_CONTRACT_RELEQUIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_BIAS> OD_BIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_CRUSHER_GRANULARITY> OD_CRUSHER_GRANULARITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_ELECTRIC_DIVIDING_MACHINE> OD_ELECTRIC_DIVIDING_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_CRUSHING_DIVIDING_MACHINE> OD_CRUSHING_DIVIDING_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_CRUSHING_MACHINE> OD_CRUSHING_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_DIEVIDER_GRANULARITY> OD_DIEVIDER_GRANULARITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_INTEGRATED_PREPARATION_MACHINE> OD_INTEGRATED_PREPARATION_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_MILLER_GRANULARITY> OD_MILLER_GRANULARITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_MILLING_MACHINE> OD_MILLING_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_MT_LOSSES> OD_MT_LOSSES { get; set; }
        public virtual OD_PRECISION OD_PRECISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_RIFFLE_DEVIDING_MACHINE> OD_RIFFLE_DEVIDING_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_SAMPLING_MACHINE> OD_SAMPLING_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_SPLITTING_RATION> OD_SPLITTING_RATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_TEST_INSTRUMENT> OD_TEST_INSTRUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_WEIGHT_LOSSES> OD_WEIGHT_LOSSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD_UNIFIED_PREPARATION_MACHINE> OD_UNIFIED_PREPARATION_MACHINE { get; set; }
    }
}
