//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_MT_LOSSES
    {
        public int ID { get; set; }
        public int OD_ID { get; set; }
        public string MT_CODE { get; set; }
        public string PALLET_CODE { get; set; }
        public decimal CONTAINER_WEIGHT { get; set; }
        public decimal SAMPLER_WEIGHT { get; set; }
        public decimal DRY_WEIGHT { get; set; }
        public decimal DRYING_CHECK1 { get; set; }
        public decimal DRYING_CHECK2 { get; set; }
        public decimal MT { get; set; }
        public string REMARK { get; set; }
        public int CREATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
    
        public virtual OD_BASIC OD_BASIC { get; set; }
    }
}
