//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_RIFFLE_DEVIDING_MACHINE
    {
        public int ID { get; set; }
        public int OD_ID { get; set; }
        public decimal SPLITTING_GRANULARITY { get; set; }
        public decimal CELL_WIDTH { get; set; }
        public int CELL_QUANTITY { get; set; }
        public string SHAPE_SIZE { get; set; }
    
        public virtual OD_BASIC OD_BASIC { get; set; }
    }
}
