//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_SPLITTING_RATION
    {
        public int ID { get; set; }
        public int OD_ID { get; set; }
        public string SPLITTING_CODE { get; set; }
        public decimal SAMPLE_WEIGHT { get; set; }
        public decimal RESERVE_WEIGHT_SAMPLE1 { get; set; }
        public decimal RESERVE_WEIGHT_SAMPLE2 { get; set; }
        public decimal RESERVE_RATION_SAMPLE1 { get; set; }
        public decimal RESERVE_RATION_SAMPLE2 { get; set; }
    
        public virtual OD_BASIC OD_BASIC { get; set; }
    }
}
