//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UM_DEPARTMENT()
        {
            this.UM_DEPARTMENT1 = new HashSet<UM_DEPARTMENT>();
        }
    
        public int ID { get; set; }
        public int FATHER_DEPARTMENT_ID { get; set; }
        public int DEPARTMENT_LEADER_ID { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string DEAPRTMENT_SHORT_NAME { get; set; }
        public string DEPARTEMNT_DESCRIPTION { get; set; }
        public int DEPARTMENT_INDEX { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public bool IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_DEPARTMENT> UM_DEPARTMENT1 { get; set; }
        public virtual UM_DEPARTMENT UM_DEPARTMENT2 { get; set; }
        public virtual UM_USERINFO UM_USERINFO { get; set; }
    }
}
