//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UM_MENU()
        {
            this.UM_MENU1 = new HashSet<UM_MENU>();
            this.UM_ROLE_RELMENU = new HashSet<UM_ROLE_RELMENU>();
        }
    
        public int ID { get; set; }
        public int FATHER_MENU_ID { get; set; }
        public string MENU_CODE { get; set; }
        public string MENU_NAME { get; set; }
        public int MENU_INDEX { get; set; }
        public string MENU_DESCRIPTION { get; set; }
        public string TRANSFER_URL { get; set; }
        public string IMG_URL { get; set; }
        public bool IS_VISIBLE { get; set; }
        public bool IS_DELETED { get; set; }
        public string REMARK { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public string CSS_CLASS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_MENU> UM_MENU1 { get; set; }
        public virtual UM_MENU UM_MENU2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_ROLE_RELMENU> UM_ROLE_RELMENU { get; set; }
    }
}
