//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_USERINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UM_USERINFO()
        {
            this.EP_EQUIPMENT_TASK = new HashSet<EP_EQUIPMENT_TASK>();
            this.EP_EQUIPMENT_TASK1 = new HashSet<EP_EQUIPMENT_TASK>();
            this.EP_EXPERIMENT_DOCUMENT = new HashSet<EP_EXPERIMENT_DOCUMENT>();
            this.UM_DEPARTMENT = new HashSet<UM_DEPARTMENT>();
            this.UM_USER_RELROLE = new HashSet<UM_USER_RELROLE>();
        }
    
        public int ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime LAST_LOGIN_TIME { get; set; }
        public int DEPARTMENT_ID { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public byte SEX { get; set; }
        public byte USER_STATUS { get; set; }
        public bool IS_DELETED { get; set; }
        public int OPERATOR_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_EQUIPMENT_TASK> EP_EQUIPMENT_TASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_EQUIPMENT_TASK> EP_EQUIPMENT_TASK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_EXPERIMENT_DOCUMENT> EP_EXPERIMENT_DOCUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_DEPARTMENT> UM_DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_USER_RELROLE> UM_USER_RELROLE { get; set; }
    }
}
