//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_USER_RELROLE
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int ROLE_ID { get; set; }
        public int CREATER_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
    
        public virtual UM_ROLE UM_ROLE { get; set; }
        public virtual UM_USERINFO UM_USERINFO { get; set; }
    }
}
